name: product_list_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  hive_ce: ^2.10.1
  cached_network_image: ^3.4.1
  pull_to_refresh: ^2.0.0
  flutter_svg: ^2.0.17
  intl: ^0.20.2
  provider: ^6.1.4
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.6
  firebase_auth: ^5.5.2
  # cloud_firestore: ^4.13.0
  # firebase_core: ^3.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_lints: ^4.0.0

flutter:


  uses-material-design: true

  assets:

    - assets/marketicons/